services:
  - type: web
    name: fullstackopen-pokedex
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start-prod
    healthCheckPath: /health
    autoDeployTrigger: off