services:
  - type: web
    name: fullstackopen-pokedex
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: node app.js
    healthCheckPath: /health
    autoDeployTrigger: off